### ISSUE TITLE
GCC build broken after 72af0a32d54e2ecca52d022d6bc635d78b8b7227

### ISSUE THREAD

**Issue by samnazarko** [palinek/pvr.sledovanitv.cz#99]
Hi,

After changes introduced in 72af0a32d54e2ecca52d022d6bc635d78b8b7227, building fails on Debian Bullseye gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

```
[ 33%] Building CXX object CMakeFiles/pvr.sledovanitv.cz.dir/src/ApiManager.cpp.o
/mnt/package/mediacenter-osmc/src/xbmc-f8fdeb6b1b1a7b753e1559d34a98cea62b4920d9/cmake/addons/build/pvr.sledovanitv.cz/src/ApiManager.cpp: In member function 'bool sledovanitvcz::ApiManager::pairDevice(Json::Value&)':
/mnt/package/mediacenter-osmc/src/xbmc-f8fdeb6b1b1a7b753e1559d34a98cea62b4920d9/cmake/addons/build/pvr.sledovanitv.cz/src/ApiManager.cpp:300:110: error: 'class std::basic_ostream<char>' has no member named 'str'
  300 |     macAddr = (std::ostringstream{} << std::chrono::high_resolution_clock::now().time_since_epoch().count()).str();
```

##### Possible Solution

basic_ostream does not have a str member. I'm guessing you are compiling with MSVC which is incorrectly returning a reference to ostringstream. 

Thanks 

Sam

**Comment by xloren09** [comment]
Hi @palinek , will this issue be resolved in the near future? Unfortunately because of this, this add-on is not included in Kodi in the current OSMC version, which makes it unusable for me. I use RaspberyPI+OSMC primarily for watching TV through this add-on.
Thanks for developing and working on this add-on!

**Comment by palinek** [comment]
This was fixed a while ago -> https://github.com/palinek/pvr.sledovanitv.cz/commit/20657a51ab71b4e07dca9284c3bf65f9a82d3c9b

**Comment by samnazarko** [comment]
This is fixed in https://github.com/osmc/osmc/commit/a83416a6578ba015f284873f1d8cda83ac75fb61.

Thanks @palinek.

**Comment by palinek** [comment]
No problem. Sorry, that I forgot to drop here the note previously.
Btw. thumbs up for the great OSMC/Vero @samnazarko

**Comment by samnazarko** [comment]
:+1:

**Comment by ZdenekM** [comment]
Great to hear that the plugin got reintroduced into OSMC. Pitty that I realized it is missing in the current version after I updated... Is there a way how to get binary/install it into 2023.06-1 (RPi3)? Or do I have to wait for the next OSMC release?

**Comment by samnazarko** [comment]
You can update it through the staging repository.
